# Generated by Django 4.2.17 on 2026-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_column='expiry_date', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateTimeField(db_column='issue_date'),
        ),
    ]
