# Generated by Django 4.2.17 on 2026-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='map_embed',
            field=models.TextField(blank=True, db_column='mapEmbed', null=True),
        ),
    ]
