# Generated by Django 4.2.17 on 2026-07-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'exam_candidates',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(db_column='option_a', max_length=255)),
                ('option_b', models.CharField(db_column='option_b', max_length=255)),
                ('option_c', models.CharField(db_column='option_c', max_length=255)),
                ('option_d', models.CharField(db_column='option_d', max_length=255)),
                ('correct_option', models.CharField(db_column='correct_option', max_length=1)),
            ],
            options={
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='ExamVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(db_column='voucher_code', max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('used_at', models.DateTimeField(blank=True, db_column='used_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('used_by_candidate', models.ForeignKey(blank=True, db_column='used_by_candidate_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.examcandidate')),
            ],
            options={
                'db_table': 'exam_vouchers',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total', models.IntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submitted_at')),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.examcandidate')),
            ],
            options={
                'db_table': 'exam_results',
            },
        ),
    ]
